server:
  port: 8761

spring:
  application:
    name: "SERVICE-REGISTRY"

  # zipkin
  zipkin:
    base-url: http://zipkin:9411/
    collector:
      host: zipkin
  sleuth:
    sampler:
      probability: 1.0

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
